name: namaz_vakti
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.0.0
  lottie: ^2.4.0
  riverpod: ^2.3.6
  shared_preferences: ^2.1.1
  country_state_city_picker: ^1.2.8
  json_serializable: ^6.7.0
  flutter_riverpod: ^2.3.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1
  json_annotation: ^4.8.1
  build_runner: ^2.4.4
  

flutter:
  uses-material-design: true

  assets: 
      - assets/

