name: namaz_vakti
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  http: ^1.1.0
  lottie: ^2.4.0
  riverpod: ^2.3.6
  shared_preferences: ^2.2.0
  json_serializable: ^6.7.0
  flutter_riverpod: ^2.3.6
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  rive: ^0.7.16
  permission_handler: ^10.3.0
  geolocator: ^9.0.2
  flutter_local_notifications: ^14.1.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  connectivity_plus: ^4.0.1
  flutter_qiblah: ^2.2.0
  flutter_svg: ^2.0.7
  quiver: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1
  json_annotation: ^4.8.1
  build_runner: ^2.4.4
  

flutter:
  uses-material-design: true

  assets: 
     - assets/
     - assets/svg/

